language: java
services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

before_script: 
  - docker-compose up -d

script:
  - ls -lah  
  - mvn test -B

after_script: 
  - docker-compose down -v 
