language: java
services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

before_install:
  - sudo add-apt-repository ppa:longsleep/golang-backports
  - sudo apt-get update
  - sudo apt install golang-go
  - go get -v -u github.com/xo/usql


install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P release
  - cp ./target/ReplicaDB-*.jar .
  - mkdir lib
  - cp ./target/lib/* ./lib
  - wget https://github.com/xo/usql/releases/download/v0.7.8/usql-0.7.8-linux-amd64.tar.bz2
  - tar -xvjf usql-0.7.8-linux-amd64.tar.bz2  

before_script: 
  - docker-compose up -d

script:
  - ls -lah  
  - mvn test -B
  - ./tests/pg2pg/run-test.sh

after_script: 
  - docker-compose down -v 
